version: "2.3.2.{build}-{branch}"

configuration: Release

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  verbosity: minimal

image: Visual Studio 2017

artifacts:
  - path: Releases
    name: Spawn.HDT.DustUtility

branches:
  only:
    - master