version: "3.0.0.{build}-{branch}"

configuration: Release

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  verbosity: normal

image: Visual Studio 2017

artifacts:
  - path: Releases
    name: Spawn.HDT.DustUtility

branches:
  only:
    - master
    - rewrite

deploy:
  release: Spawn.HDT.DustUtility v$(appveyor_build_version)
  description: '<ADD DESCRIPTION>'
  provider: GitHub
  auth_token:
    secure: o8qzkmoJtqt3CjSyS2EzkSRn/d2lYpi6kqt/q7NH1EiMeuoum6Y7pT/HcwsRhd+M
  draft: true
  on:
    appveyor_repo_tag: true